name: requirements-analyst

services:
  app:
    build: .
    container_name: requirements_analyst_app
    ports:
      - "5001:5001"
    volumes:
      - ./requirements_analyst/instance:/app/instance
    environment:
      - FLASK_ENV=production
    restart: unless-stopped